### Fetch all cars
GET http://localhost:3000/api/cars
Accept: application/json

### Fetch most popular make
GET http://localhost:3000/api/most-popular-make
Accept: application/json

### Create a new car
POST http://localhost:3000/api/cars
Content-Type: application/json

{
  "make": "Honda",
  "model": "Civic",
  "color": "Black"
}

### Update an existing car (Change ID accordingly)
PUT http://localhost:3000/api/cars/1
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Camry",
  "color": "Red"
}

### Delete a car (Change ID accordingly)
DELETE http://localhost:3000/api/cars/1
Accept: application/json

### Fetch all cars again to see the changes
GET http://localhost:3000/api/cars
Accept: application/json

### Fetch most popular make after adding/deleting a car
GET http://localhost:3000/api/most-popular-make
Accept: application/json
